# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UXg_nsoB6Z0hmqxFJ-1Ig5XNE9HET8n0
"""

# ==========================================
# Flight Price Model Training
# ==========================================

import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# ------------------------------------------
# Load processed dataset
# ------------------------------------------

df = pd.read_csv("processed_data.csv")

print(df.head())

# ------------------------------------------
# Encode categorical columns
# ------------------------------------------

label_encoders = {}

for col in df.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# ------------------------------------------
# Select Target Column
# ------------------------------------------

TARGET_COLUMN = "price"      # <-- Change if needed

X = df.drop(TARGET_COLUMN, axis=1)
y = df[TARGET_COLUMN]

# ------------------------------------------
# Train-Test Split
# ------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# ------------------------------------------
# Train Model
# ------------------------------------------

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

# ------------------------------------------
# Prediction
# ------------------------------------------

pred = model.predict(X_test)

print("\nMAE:", mean_absolute_error(y_test, pred))

# ------------------------------------------
# Save Model
# ------------------------------------------

joblib.dump(model, "classifier.pkl")

print("\nModel saved successfully!")